name: Trigger auto deployment for youtube-playlist-creator-v2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/youtube-playlist-creator-v2-AutoDeployTrigger-9496f3e1-7e2a-43dc-9949-a55fba0ec686.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.YOUTUBEPLAYLISTCREATORV2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.YOUTUBEPLAYLISTCREATORV2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.YOUTUBEPLAYLISTCREATORV2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.YOUTUBEPLAYLISTCREATORV2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOUTUBEPLAYLISTCREATORV2_REGISTRY_PASSWORD }}
          containerAppName: youtube-playlist-creator-v2
          resourceGroup: resource1
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


